---
startBlock: "64500"
blockEnd: "66500"
storage: "ELASTICSEARCH"
targetNode: "http://192.168.10.129:32773/"
os: "WINDOWS"
txIndex: "ether-trans4"
blockIndex: "eth-blocks"
backpressureBlocks: 8
backPressureTx: 20
txImport: true
blockImport: true
