---
startBlock: "64500"
blockEnd: "66500"
storage: "ELASTICSEARCH"
targetNode: "http://localhost:8545/"
os: "WINDOWS"
txIndex: "ether-tx"
blockIndex: "ether-blocks"
backpressureBlocks: 8
backPressureTx: 20
txImport: true
blockImport: true
